[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
skip-string-normalization = true
verbose = true
exclude = '''
/(
  \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | \.serverless
  | node_modules
)/
'''
