service: watcher

frameworkVersion: ">=1.65.0"

custom:
  stage_long:
    dev: development
    prod: production
  account_id: ${opt:account_id, '028920223318'}
  lambdaArnPrefix: arn:aws:lambda:${self:provider.region}:${self:custom.account_id}:function:${self:service}-${self:provider.stage}
  snsArnPrefix: arn:aws:sns:${self:provider.region}:${self:custom.account_id}
  pythonRequirements:
    usePoetry: false
    dockerizePip: true
  datadog:
    addLayers: true
    apiKey: ${ssm:/clowd/datadog_api_key~true}
    flushMetricsToLogs: false

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  timeout: 5
  memorySize: 256
  logRetentionInDays: 30
  deploymentBucket:
    name: serverless-${self:custom.account_id}-${self:provider.region}
    serverSideEncryption: AES256
  versionFunctions: false
  environment:
    STAGE: ${opt:stage, 'dev'}
    REGION: ${self:provider.region}
    SNS_ARN_PREFIX: ${self:custom.snsArnPrefix}
    PYTHONWARNINGS: ignore # https://github.com/jmespath/jmespath.py/issues/187
  tags:
    service: watcher
    environment: ${self:custom.stage_long.${self:provider.stage}}
    createdby: serverless
    repository: https://github.com/clowdhaus/watcher
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource:
        - "*"

layers:
  watcherCore:
    package:
      artifact: layers/core/core.zip
    description: Lambda layer containing core python libraries
    compatibleRuntimes:
      - python3.8
    retain: false

package:
  exclude:
    - "**/*"
  include:
    - lambdas/*.py

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-datadog
  - serverless-python-requirements

functions:
  hubReceive:
    handler: lambdas/hub.receive
    layers:
      - { Ref: WatcherCoreLambdaLayer }
    description: Receive and validate GitHub webhooks before passing along payload
    iamRoleStatementsInherit: true
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-hub-receive
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:us-east-1:${self:custom.account_id}:parameter/watcher/github_webhook_secret
      - Effect: Allow
        Action:
          - sns:Publish
        Resource:
          - "${self:custom.snsArnPrefix}:Watcher-*"
    events:
      - http:
          path: watcher
          method: post

  hubNewTag:
    handler: lambdas/versions.new_tag
    layers:
      - { Ref: WatcherCoreLambdaLayer }
    timeout: 60
    memorySize: 512
    description: Responds to new tag events
    iamRoleStatementsInherit: true
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-hub-new-tag
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:us-east-1:${self:custom.account_id}:parameter/watcher/github_user_token
    events:
      - sns:
          topicName: Watcher-Tag
          displayName: Contains tag event payloads

  hubCreateRelease:
    handler: lambdas/versions.create_release
    layers:
      - { Ref: WatcherCoreLambdaLayer }
    description: Responds to new tag events to create a release
    iamRoleStatementsInherit: true
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-hub-create-release
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:us-east-1:${self:custom.account_id}:parameter/watcher/github_user_token
    events:
      - sns:
          topicName: Watcher-Tag
          displayName: Contains tag event payloads

  hubPullRequest:
    handler: lambdas/pull_requests.pull_request
    layers:
      - { Ref: WatcherCoreLambdaLayer }
    timeout: 60
    memorySize: 512
    description: Responds to pull request events
    iamRoleStatementsInherit: true
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-hub-pull-request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:us-east-1:${self:custom.account_id}:parameter/watcher/github_user_token
    events:
      - sns:
          topicName: Watcher-Pull-Request
          displayName: Contains pull request event payloads
