name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy watcher to AWS environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: clowdhaus/aws-github-actions/packages/iam_access_credentials@v0.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Uses Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install yarn and dependencies
        run: |
          npm install -g yarn
          pip install pipenv
          yarn
          make generate_artifacts
      - name: Deploy watcher core lambda layer only if changes made to layer
        run: |
          LATEST_COMMIT=$(git rev-parse HEAD)
          LATEST_COMMIT_IN_PATH=$(git log -1 --format=format:%H --full-diff layers/core layer_core.yml)
          if [ $LATEST_COMMIT == $LATEST_COMMIT_IN_PATH ]; then
            yarn run sls deploy -c layer_core.yml
          fi
      - name: Deploy watcher service to AWS
        run: yarn run sls deploy
